### ISSUE TITLE
rpmlint reports  E: non-executable-script

### ISSUE THREAD

**Issue by martinkg** [smolleyes/gmediafinder2#1]
rpmlint reports a few errors with the recent Gmediafinder 1.0.1

gmediafinder.noarch: E: non-executable-script /usr/lib/python2.7/site-packages/GmediaFinder/engines.py 0644L /usr/bin/env
gmediafinder.noarch: E: non-executable-script /usr/lib/python2.7/site-packages/GmediaFinder/Translation.py 0644L /usr/bin/python
gmediafinder.noarch: E: non-executable-script /usr/lib/python2.7/site-packages/GmediaFinder/pykey.py 0644L /usr/bin/env
gmediafinder.noarch: E: non-executable-script /usr/lib/python2.7/site-packages/GmediaFinder/checklinks.py 0644L /usr/bin/env
gmediafinder.noarch: E: non-executable-script /usr/lib/python2.7/site-packages/GmediaFinder/gmediafinder.py 0644L /usr/bin/env

can be solved with chmod a+x $filenames

same is with the files, they need  chmod 644 $filenames

gpl-2.0.txt
CHANGELOG'  
README'  
VERSION
**init**.py
mainGui.glade'

the desktop file needed a ; at line Categries

--- gmediafinder/gmediafinder.desktop.orig  2012-10-14 18:52:50.921645763 +0200
+++ gmediafinder/gmediafinder.desktop   2012-10-14 18:53:00.106647272 +0200
@@ -7,5 +7,5 @@
 Terminal=false
 X-MultipleArgs=false
 Type=Application
-Categories=AudioVideo
+Categories=AudioVideo;
 Name[fr_FR]=Gmediafinder

hope you can fix this for next release.

**Comment by smolleyes** [comment]
hi

i tried to fix as you told me ...

for a friend he has (i m not on rpm system...):

rpmlint -i gmediafinder
gmediafinder.noarch: W: spelling-error %description -l en_US youtube -> you tube, you-tube, buyout

gmediafinder.noarch: W: spelling-error %description -l en_US google -> Google, goggle, go ogle

gmediafinder.noarch: W: spelling-error %description -l en_US searchengines -> search engines, search-engines, searchings

gmediafinder.noarch: W: spelling-error %description -l en_US fullscreen -> full screen, full-screen, silkscreen

gmediafinder.noarch: W: spelling-error %description -l en_US visualisation -> visualization, salivation, nationalist

gmediafinder.noarch: W: spelling-error %description -l en_US gstreamer -> streamer, g streamer, streamed

gmediafinder.noarch: W: spelling-error %description -l en_US prefered -> preferred, prefer ed, prefer-ed

gmediafinder.noarch: W: spelling-error %description -l en_US cpu -> CPU, cup, cu

gmediafinder.noarch: W: spelling-error %description -l en_US flv -> fl, flt, flu

1 packages and 0 specfiles checked; 0 errors , 9 warnings.

++
