### ISSUE TITLE
rpmlint errors on Fedora 17 and 18

### ISSUE THREAD

**Issue by martinkg** [smolleyes/gmediafinder2#2]
Hi,
rpmlint reports also with gmediafinder-1.0.3 the rpmlint errors

I have used the following comand to build from sources
git clone git://github.com/smolleyes/gmediafinder2.git

rpmlint gmediafinder-1.0.3-1.fc18.noarch.rpm
gmediafinder.noarch: W: spelling-error %description -l en_US gstreamer -> streamer, g streamer, steamer
gmediafinder.noarch: W: spelling-error %description -l en_US flv -> fl, flt, flu
gmediafinder.noarch: E: script-without-shebang /usr/share/pyshared/GmediaFinder/lib/engines/**init**.py
gmediafinder.noarch: W: spurious-executable-perm /usr/share/doc/gmediafinder-1.0.3/CHANGELOG
gmediafinder.noarch: E: script-without-shebang /usr/share/gmediafinder/glade/mainGui.glade
gmediafinder.noarch: W: spurious-executable-perm /usr/share/doc/gmediafinder-1.0.3/README
gmediafinder.noarch: W: spurious-executable-perm /usr/share/doc/gmediafinder-1.0.3/VERSION
gmediafinder.noarch: W: spurious-executable-perm /usr/share/doc/gmediafinder-1.0.3/gpl-2.0.txt
gmediafinder.noarch: E: script-without-shebang /usr/share/pyshared/GmediaFinder/lib/**init**.py
gmediafinder.noarch: E: script-without-shebang /usr/share/pyshared/GmediaFinder/**init**.py
gmediafinder.noarch: W: no-manual-page-for-binary gmediafinder
gmediafinder.noarch: E: invalid-desktopfile /usr/share/applications/gmediafinder.desktop value "AudioVideo" for string list key "Categories" in group "Desktop Entry" does not have a semicolon (';') as trailing character
1 packages and 0 specfiles checked; 5 errors, 7 warnings.

necessary workaround at the moment for me:

--- gmediafinder/gmediafinder.desktop.orig  2012-10-14 18:52:50.921645763 +0200
+++ gmediafinder/gmediafinder.desktop   2012-10-14 18:53:00.106647272 +0200
@@ -7,5 +7,5 @@
 Terminal=false
 X-MultipleArgs=false
 Type=Application
-Categories=AudioVideo
+Categories=AudioVideo;
 Name[fr_FR]=Gmediafinder

and
# fix permissions

find . -name 'gpl-2.0.txt' -exec chmod 644 '{}' \;
find . -name 'CHANGELOG' -exec chmod 644 '{}' \;
find . -name 'README' -exec chmod 644 '{}' \;
find . -name 'VERSION' -exec chmod 644 '{}' \;
find . -name '**init**.py' -exec chmod 644 '{}' \;
find . -name 'mainGui.glade' -exec chmod 644 '{}' \;

**Comment by martinkg** [comment]
please ignore my previous message.
This are the new rpmlint error message with version 1.0.3

rpmlint gmediafinder-1.0.3-1.fc18.noarch.rpm
gmediafinder.noarch: W: spelling-error %description -l en_US gstreamer -> streamer, g streamer, steamer
gmediafinder.noarch: W: spelling-error %description -l en_US flv -> fl, flt, flu
gmediafinder.noarch: E: non-executable-script /usr/lib/python2.7/site-packages/GmediaFinder/lib/checklinks.py 0644L /usr/bin/env
gmediafinder.noarch: E: non-executable-script /usr/share/gmediafinder/scripts/get_stream.py 0644L /usr/bin/env
gmediafinder.noarch: E: non-executable-script /usr/lib/python2.7/site-packages/GmediaFinder/lib/engines/**init**.py 0644L /usr/bin/env
gmediafinder.noarch: E: non-executable-script /usr/lib/python2.7/site-packages/GmediaFinder/lib/get_stream.py 0644L /usr/bin/env
gmediafinder.noarch: E: non-executable-script /usr/lib/python2.7/site-packages/GmediaFinder/**init**.py 0644L /usr/bin/env
gmediafinder.noarch: E: non-executable-script /usr/lib/python2.7/site-packages/GmediaFinder/lib/downloads/**init**.py 0644L /usr/bin/env
gmediafinder.noarch: E: non-executable-script /usr/lib/python2.7/site-packages/GmediaFinder/lib/Translation.py 0644L /usr/bin/python
gmediafinder.noarch: E: non-executable-script /usr/lib/python2.7/site-packages/GmediaFinder/lib/**init**.py 0644L /usr/bin/env
gmediafinder.noarch: E: non-executable-script /usr/lib/python2.7/site-packages/GmediaFinder/lib/engines/main.py 0644L /usr/bin/env
gmediafinder.noarch: E: non-executable-script /usr/lib/python2.7/site-packages/GmediaFinder/lib/player/**init**.py 0644L /usr/bin/env
gmediafinder.noarch: E: non-executable-script /usr/lib/python2.7/site-packages/GmediaFinder/gmediafinder.py 0644L /usr/bin/env
gmediafinder.noarch: E: non-executable-script /usr/lib/python2.7/site-packages/GmediaFinder/lib/pykey.py 0644L /usr/bin/env
gmediafinder.noarch: W: no-manual-page-for-binary gmediafinder
1 packages and 0 specfiles checked; 12 errors, 3 warnings.

I solved this at the moment with the following command:

chmod a+x $RPM_BUILD_ROOT/usr/share/gmediafinder/scripts/get_stream.py
for file in $RPM_BUILD_ROOT%{python_sitelib}/GmediaFinder/{lib/checklinks,lib/engines/**init**,lib/get_stream,**init**,lib/downloads/**init**,lib/Translation,lib/**init**,lib/engines/main,lib/player/**init**,gmediafinder,lib/pykey}.py; do
    chmod a+x $file
done

**Comment by smolleyes** [comment]
hi

i added a gmediafinder.spec file in the git use it to build your rpm packages :)

++

**Comment by martinkg** [comment]
thanks for the spec file, but this works not on Fedora, but no problem.
I am working on a rpm package review for fedora rpmfusion, and on the link, there is a working one.

https://bugzilla.rpmfusion.org/show_bug.cgi?id=2532

please correct the download link in your spec file.

# Obtaining source

# git clone git://github.com/smolleyes/gmediafinder2.git && tar cjf gmediafinder-%%{version}.tar.bz2 gmediafinder && rm -rf gmediafinder

**Comment by smolleyes** [comment]
hello

fixed in the git

thanks :)

**Comment by martinkg** [comment]
you should change your git command in the spec file

git clone git://github.com/smolleyes/gmediafinder2.git gmediafinder; tar cjf gmediafinder-%%{version}.tar.bz2 gmediafinder; rm -rf gmediafinder

and change the
Source0:        https://nodeload.github.com/smolleyes/gmediafinder2/%{name}-%{version}.tar.gz
to
Source0:        %{name}-%{version}.tar.bz2

because the mentioned link doesn't exists.

**Comment by smolleyes** [comment]
hello

done 

;)

**Comment by martinkg** [comment]
sorry if i notice on thing again:
1. you create in your obtain example a tar.bz2 file, but use in the Source a tar.gz
2. your command "git clone git://github.com/smolleyes/gmediafinder2.git" creates a folder gmediafinder2

#Obtaining source
#git clone git://github.com/smolleyes/gmediafinder2.git && tar cjf gmediafinder-%%{version}.tar.bz2 gmediafinder && rm -rf gmediafinder
Source0: %{name}-%{version}.tar.gz

change it to:
#git clone git://github.com/smolleyes/gmediafinder2.git gmediafinder && tar cjf gmediafinder-%%{version}.tar.bz2 gmediafinder && rm -rf gmediafinder
Source0: %{name}-%{version}.tar.bz2

thanks
