### ISSUE TITLE
gmediafinder didn't start with german menu text

### ISSUE THREAD

**Issue by martinkg** [smolleyes/gmediafinder2#3]
with the recent gmediafinder-1.0.3 the program didn't start with german menu text.

the language is set as following: 
env |grep LANG
LANG=de_DE.UTF-8

all lang packages ar installed:

/usr/share/locale/ar/LC_MESSAGES/gmediafinder.mo
/usr/share/locale/cs_CZ/LC_MESSAGES/gmediafinder.mo
/usr/share/locale/de_DE/LC_MESSAGES/gmediafinder.mo
/usr/share/locale/en/LC_MESSAGES/gmediafinder.mo
/usr/share/locale/es/LC_MESSAGES/gmediafinder.mo
/usr/share/locale/fr/LC_MESSAGES/gmediafinder.mo
/usr/share/locale/gl/LC_MESSAGES/gmediafinder.mo
/usr/share/locale/it/LC_MESSAGES/gmediafinder.mo
/usr/share/locale/pl_PL/LC_MESSAGES/gmediafinder.mo
/usr/share/locale/ro/LC_MESSAGES/gmediafinder.mo
/usr/share/locale/ru/LC_MESSAGES/gmediafinder.mo
/usr/share/locale/sr/LC_MESSAGES/gmediafinder.mo
/usr/share/locale/zh_CN/LC_MESSAGES/gmediafinder.mo

any hint ?

**Comment by martinkg** [comment]
please can you verify this ?

**Comment by martinkg** [comment]
i have alread tranlated the gemedia menu text on
https://www.transifex.com/projects/p/gmf/resource/gmediafinderpot/
but if i list gmediafinder.mo, there are significant differences in the file size

[martin@fc17-64 gmediafinder]$ ll po/fr/LC_MESSAGES/gmediafinder.mo
-rw-r--r--. 1 martin martin 15567 19. Okt 18:45 po/fr/LC_MESSAGES/gmediafinder.mo
[martin@fc17-64 gmediafinder]$ ll po/it/LC_MESSAGES/gmediafinder.mo
-rw-r--r--. 1 martin martin 14406 19. Okt 18:45 po/it/LC_MESSAGES/gmediafinder.mo
[martin@fc17-64 gmediafinder]$ ll po/de_DE/LC_MESSAGES/gmediafinder.mo
-rw-r--r--. 1 martin martin 371 19. Okt 18:45 po/de_DE/LC_MESSAGES/gmediafinder.mo

**Comment by martinkg** [comment]
please use the correct de_DE.po file in your sources.
https://www.transifex.com/projects/p/gmf/resource/gmediafinderpot/l/de_DE/download/for_use/
Thanks.

**Comment by smolleyes** [comment]
hello

strange.. i changed the de file in the git..tell me if it works

thanks

**Comment by martinkg** [comment]
now it works perfect, all menus are in german.
thanks

**Comment by smolleyes** [comment]
np 

thank you too :p 

++
