### ISSUE TITLE
Gmediafinder does not start on Fedora 18 (pywebkitgtk installed)

### ISSUE THREAD

**Issue by Milozzy** [smolleyes/gmediafinder2#5]
Hi!
If I try to run gmediafinder it does not start and from the terminal I
get this output:

$ gmediafinder 
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
Traceback (most recent call last):
  File "/usr/bin/gmediafinder", line 22, in <module>
    from GmediaFinder import gmediafinder
  File "/usr/lib/python2.7/site-packages/GmediaFinder/gmediafinder.py", line
53, in <module>
    from GmediaFinder.lib.engines import Engines
ImportError: cannot import name Engines

My system is Fedora 18 Gnome x86_64, I already submitted the bug to the Fedora mainteiner, but we can't solved the issue. You can find the bug report and what we tried here: https://bugzilla.rpmfusion.org/show_bug.cgi?id=2770

Thanks!

**Comment by smolleyes** [comment]
hi 

not at home now can t see the bug and i don t use fedora 

open gmediafinder.py and at the begining copy all the import ...... between the first try: and except: and past them before the try: then run python gmediafinder.py again we ll have more clear infos ... sorry if i m not very clear :p let me know 

++

Envoyé de mon iPhone

**Comment by Milozzy** [comment]
Thanks for your reply!
I hope I get it right, this is how I edited gmediafinder.py

---

#!/usr/bin/env python
#-_\- coding: UTF-8 -_-

import sys
import glib
import pango
import os
import thread
import threading
import random
import time
import gobject
gobject.threads_init()
import pygtk
pygtk.require('2.0')
import gtk
import gtk.glade
import gtk.gdk
import urllib
import pygst
pygst.require("0.10")
import gst
import mechanize
import gdata
import math

## for win32...py2exe

import json
import gdata.youtube.service as yt_service
import gettext
import time
import locale
import Queue
import cairo
import pangocairo
import lib.debrid as debrider
from lib.downloads import downloader
from lib.player.player_gui import Player
from lib.config import *
from lib.engines.main import Engines
from lib.functions import *
from lib.playlist import Playlist
if sys.platform != "win32":
    from lib.pykey import send_string
import lib.checklinks as checkLink
from lib.get_stream import Browser as browser

if sys.platform == "win32":
    import win32api

try:
    import lib.debrid as debrider
    from lib.downloads import downloader
    from lib.player.player_gui import Player
    from lib.config import *
    from lib.engines.main import Engines
    from lib.functions import *
    from lib.playlist import Playlist
    if sys.platform != "win32":
        from lib.pykey import send_string
    import lib.checklinks as checkLink
    from lib.get_stream import Browser as browser
except:
    from GmediaFinder.lib.config import *
    from GmediaFinder.lib.engines import Engines
    from GmediaFinder.lib.functions import *
    from GmediaFinder.lib.playlist import Playlist
    if sys.platform != "win32":
        from GmediaFinder.lib.pykey import send_string
    import GmediaFinder.lib.debrid as debrider
    import GmediaFinder.lib.checklinks as checkLink
    from GmediaFinder.lib.player.player_gui import Player
    from GmediaFinder.lib.downloads import downloader
    from GmediaFinder.lib.get_stream import Browser as browser
    from GmediaFinder.lib.engines.main import Engines

---

And this is the results:

---

$ python gmediafinder.py 
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
Traceback (most recent call last):
  File "gmediafinder.py", line 37, in <module>
    from lib.player.player_gui import Player
  File "/home/milo/gmediafinder/GmediaFinder/lib/player/player_gui.py", line 28, in <module>
    from GmediaFinder.lib.pykey import send_string
  File "/usr/lib/python2.7/site-packages/GmediaFinder/lib/pykey.py", line 11, in <module>
    import Xlib.display
ImportError: No module named Xlib.display

---

Thanks!!!

**Comment by smolleyes** [comment]
hi

python-xlib installed ?

Envoyé de mon iPhone

**Comment by Milozzy** [comment]
Great!! This solved the problem!!
I will report that to the Fedora mainteiner so he can add python-xlib as a dependency!
Thankyou very very much

**Comment by smolleyes** [comment]
hi m8

just made a big update for gmediafinder ;)

can now start videos from gmf or integrated browser  

++
